openapi: "3.0.0"
info:
    title: The NBA team api
    version: "1.0.0"
paths: 
  /v1/nba/teams:
    get:
      parameters:
        - name: title
          in: query
          description: filter field in list of team
          required: false
          example: Boston
          schema:
            type: string
      responses:
        "200":
          description: returns the list of NBA team
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    team_id: 
                      type: number
                    team_name:
                      type: string
                    simple_name: 
                      type: string
                    location:
                      type: string
    